### ISSUE TITLE
Incorrect syntax highlighting with es6 arrow functions

### ISSUE THREAD

**Issue by redbmk** [neoclide/vim-jsx-improve#34]
When using an arrow function within a JSX tag, vim tries to match the `>` from the `=>` to the element's opening `<` tag. I think this might be somewhat related to #28 (thanks for fixing that btw, I just switched from `vim-jsx` and the highlighting is much better now :)

Here's a basic example you can use: 

```
  <button onClick={() => this.setState({ clicked: true })}>Click Me</button>
```

I'd imagine there's a way you could tell it to ignore the `>` if it immediately follows a `=`, but I don't even know where to start.

You also see this type of syntax in render props a lot. For example, in the first example of [React Final Form in Getting Started](https://github.com/final-form/react-final-form#getting-started) I would expect hitting `%` on the `<` from `<Form` would move the cursor to the very end `>` tag, but instead it goes to the first `=>`. It actually highlights the proper bracket when your cursor is on the either end, but it also matches the first bracket if your cursor is on the end bracket from the first `=>`.

It sounds like in #28 you were saying this could be part of `matchparen`, but I'm wondering if it could be fixed here since it seems pretty specific to JSX.

**Comment by chemzqm** [comment]
It's fixed in vim-jsx-improve.
I could use `%` to jump between matched tag with 
```
  <button onClick={() => this.setState({ clicked: true })}>Click Me</button>
```
Maybe caused by using vim-jsx-improve with pangloss/vim-javascript?

**Comment by chemzqm** [comment]
I've noticed there is incorrect highlight with arrow function in jsx attribute.

**Comment by redbmk** [comment]
I'm using `vim-jsx-improve`, with `vim-javascript` disabled. I just tried disabling all my plugins aside from `vim-jsx-improve` and `gruvbox`, but I'm still seeing the issue. I'm running on the latest master branch.

![vim-jsx-improve-highlighting](https://user-images.githubusercontent.com/83964/43473063-fa87db84-94a3-11e8-9978-35b45e0f44d7.gif)

**Comment by chemzqm** [comment]
Get it, `matchit.vim` doesn't work as expected for jump between  `<` and `>` tag.
It could be improved to check the if the match have the same syntax name.

**Comment by redbmk** [comment]
You're amazing! ❤️
